version: '3.7'

services:
    db:
        image: postgres:10.1-alpine
        ports:
          - "5432:5432"
    bot:
        build: .
        command: python schedule_job.py
        volumes: 
            - .:/app/
        depends_on: 
            - db